"""BPF C code generator.

Given an analyzed AST, emits a C source string that clang compiles to
a verifier-accepted XDP program. Bounds checks at every layer; IPv4
IHL handled correctly; TCP/UDP ports in host byte order.

The emitter analyzes the program once to decide which protocol layers
need parsing. Layers not referenced are skipped to keep the BPF
instruction budget low. Each parse step gates its pointer dereference
with an inline bounds check; on failure, the relevant field defaults
to 0 (or the rule's condition naturally evaluates to false).
"""
from __future__ import annotations

from . import ast


_PROTO_TO_IPPROTO = {
  ast.Proto.TCP: "IPPROTO_TCP",
  ast.Proto.UDP: "IPPROTO_UDP",
  ast.Proto.ICMP: "IPPROTO_ICMP",
}


_HEADER = """\
// Generated by fwl. Do not edit.

#include <linux/bpf.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/in.h>
#include <linux/tcp.h>
#include <linux/udp.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_endian.h>

struct fwl_rl_state {
  __u64 ts;
  __u32 count;
};
"""


_RL_FIELD_TO_C = {
  "src_ip": "src_ip",
  "dst_ip": "dst_ip",
  "src_port": "src_port",
  "dst_port": "dst_port",
}


# Map the per= field name to the AST field name so _referenced_fields
# can include modifier-keyed fields in its parse-prelude analysis.
_RL_FIELD_TO_AST = {
  "src_ip": ast.FIELD_SRC_IP,
  "dst_ip": ast.FIELD_DST_IP,
  "src_port": ast.FIELD_SRC_PORT,
  "dst_port": ast.FIELD_DST_PORT,
}


_TERMINAL_ACTION_TO_RETURN = {
  ast.Action.ALLOW: "XDP_PASS",
  ast.Action.DROP: "XDP_DROP",
}


_LOG_EVENT_DECL = """\
struct fwl_log_event {
  __u64 timestamp_ns;
  __u32 src_ip;
  __u32 dst_ip;
  __u16 src_port;
  __u16 dst_port;
  __u8  proto;
  __u8  flags;
  __u32 rule_index;
};

struct {
  __uint(type, BPF_MAP_TYPE_RINGBUF);
  __uint(max_entries, 1 << 20);
} fwl_log_events SEC(".maps");
"""


_COUNTER_MAP_DECL_TEMPLATE = """\
struct {{
  __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
  __type(key, __u32);
  __type(value, __u64);
  __uint(max_entries, {n_slots});
}} fwl_counters SEC(".maps");
"""


def _walk(node) -> list:
  """Yield all sub-conditions of `node` in pre-order."""
  if node is None:
    return []
  out = [node]
  if isinstance(node, ast.NotOp):
    out.extend(_walk(node.inner))
  elif isinstance(node, (ast.AndOp, ast.OrOp)):
    for child in node.operands:
      out.extend(_walk(child))
  return out


def _referenced_fields(program: ast.Program) -> set[str]:
  """Set of pkt.* field names mentioned anywhere in the program.

  Includes fields used in conditions, rate_limit bucket keys, AND log
  events (the log_event struct carries every L4 field). Any program
  with a `log` rule needs the full prelude.
  """
  fields: set[str] = set()
  has_log = False
  for rule in program.rules:
    for n in _walk(rule.condition):
      if isinstance(n, ast.Comparison):
        fields.add(n.field.name)
      elif isinstance(n, ast.BoolField):
        fields.add(n.field.name)
    if rule.modifier is not None:
      fields.add(_RL_FIELD_TO_AST[rule.modifier.per_field])
    if rule.action == ast.Action.LOG:
      has_log = True
  if has_log:
    fields.update({
      ast.FIELD_SRC_IP, ast.FIELD_DST_IP,
      ast.FIELD_SRC_PORT, ast.FIELD_DST_PORT,
      ast.FIELD_TCP_SYN, ast.FIELD_TCP_ACK,
    })
  return fields


def _needs_l4(fields: set[str]) -> bool:
  """True iff any port or TCP-flag field is referenced."""
  return bool(fields & (ast.PORT_FIELDS | ast.TCP_FLAG_FIELDS))


def _needs_tcp(fields: set[str]) -> bool:
  """True iff any TCP-flag field is referenced."""
  return bool(fields & ast.TCP_FLAG_FIELDS)


def _emit_parse_prelude(program: ast.Program) -> str:
  """Emit the packet-parsing prelude.

  Initializes all referenced fields to 0 and overwrites them only
  when each parse step succeeds. Truncated or non-IPv4 packets fall
  through to subsequent rules (and the default) per
  FWL_V01_SPEC.md:185-191.
  """
  fields = _referenced_fields(program)
  if not fields:
    return ""

  needs_l4 = _needs_l4(fields)
  needs_tcp = _needs_tcp(fields)

  decls: list[str] = ["__u8 proto = 0;"]
  if ast.FIELD_SRC_IP in fields:
    decls.append("__u32 src_ip = 0;")
  if ast.FIELD_DST_IP in fields:
    decls.append("__u32 dst_ip = 0;")
  if ast.FIELD_SRC_PORT in fields:
    decls.append("__u16 src_port = 0;")
  if ast.FIELD_DST_PORT in fields:
    decls.append("__u16 dst_port = 0;")
  if ast.FIELD_TCP_SYN in fields:
    decls.append("__u8 tcp_syn = 0;")
  if ast.FIELD_TCP_ACK in fields:
    decls.append("__u8 tcp_ack = 0;")

  decl_block = "\n".join("  " + d for d in decls)

  ip_reads = []
  if ast.FIELD_SRC_IP in fields:
    ip_reads.append("        src_ip = bpf_ntohl(ip->saddr);")
  if ast.FIELD_DST_IP in fields:
    ip_reads.append("        dst_ip = bpf_ntohl(ip->daddr);")
  ip_read_block = "\n".join(ip_reads)
  if ip_read_block:
    ip_read_block = "\n" + ip_read_block

  l4_block = ""
  if needs_l4:
    # Variable IHL: L4 starts at ip + ihl*4.
    port_reads_tcp = []
    port_reads_udp = []
    if ast.FIELD_SRC_PORT in fields:
      port_reads_tcp.append(
        "              src_port = bpf_ntohs(tcp->source);"
      )
      port_reads_udp.append(
        "              src_port = bpf_ntohs(udp->source);"
      )
    if ast.FIELD_DST_PORT in fields:
      port_reads_tcp.append(
        "              dst_port = bpf_ntohs(tcp->dest);"
      )
      port_reads_udp.append(
        "              dst_port = bpf_ntohs(udp->dest);"
      )
    tcp_flag_reads = []
    if needs_tcp:
      if ast.FIELD_TCP_SYN in fields:
        tcp_flag_reads.append("              tcp_syn = tcp->syn;")
      if ast.FIELD_TCP_ACK in fields:
        tcp_flag_reads.append("              tcp_ack = tcp->ack;")
    tcp_branch = "\n".join(port_reads_tcp + tcp_flag_reads)
    udp_branch = "\n".join(port_reads_udp)

    tcp_block = ""
    if tcp_branch:
      tcp_block = f"""
          if (proto == IPPROTO_TCP) {{
            struct tcphdr *tcp = (void *)ip + ip_hlen;
            if ((void *)(tcp + 1) <= data_end) {{
{tcp_branch}
            }}
          }}"""

    udp_block = ""
    if udp_branch:
      udp_block = f"""
          if (proto == IPPROTO_UDP) {{
            struct udphdr *udp = (void *)ip + ip_hlen;
            if ((void *)(udp + 1) <= data_end) {{
{udp_branch}
            }}
          }}"""

    l4_block = f"""
        __u32 ip_hlen = ip->ihl * 4;
        if (ip_hlen >= sizeof(struct iphdr) &&
            (void *)ip + ip_hlen <= data_end) {{{tcp_block}{udp_block}
        }}"""

  return f"""\
{decl_block}
  void *data = (void *)(long)ctx->data;
  void *data_end = (void *)(long)ctx->data_end;
  struct ethhdr *eth = data;
  if ((void *)(eth + 1) <= data_end) {{
    if (eth->h_proto == bpf_htons(ETH_P_IP)) {{
      struct iphdr *ip = (void *)(eth + 1);
      if ((void *)(ip + 1) <= data_end) {{
        proto = ip->protocol;{ip_read_block}{l4_block}
      }}
    }}
  }}

"""


def _emit_condition(node: ast.Condition) -> str:
  """Emit a C boolean expression for `node`. Parens for safety."""
  if isinstance(node, ast.Comparison):
    return _emit_comparison(node)
  if isinstance(node, ast.BoolField):
    return _emit_bool_field(node)
  if isinstance(node, ast.NotOp):
    return f"!({_emit_condition(node.inner)})"
  if isinstance(node, ast.AndOp):
    parts = [_emit_condition(c) for c in node.operands]
    return "(" + " && ".join(parts) + ")"
  if isinstance(node, ast.OrOp):
    parts = [_emit_condition(c) for c in node.operands]
    return "(" + " || ".join(parts) + ")"
  raise NotImplementedError(
    f"emitter: unsupported condition {type(node).__name__}"
  )


def _emit_bool_field(node: ast.BoolField) -> str:
  """Emit a C expression for a bare bool field."""
  if node.field.name == ast.FIELD_TCP_SYN:
    return "tcp_syn"
  if node.field.name == ast.FIELD_TCP_ACK:
    return "tcp_ack"
  raise NotImplementedError(
    f"emitter: unsupported bool field {node.field.name}"
  )


_FIELD_TO_C = {
  ast.FIELD_PROTO: "proto",
  ast.FIELD_SRC_IP: "src_ip",
  ast.FIELD_DST_IP: "dst_ip",
  ast.FIELD_SRC_PORT: "src_port",
  ast.FIELD_DST_PORT: "dst_port",
}


def _emit_comparison(cmp: ast.Comparison) -> str:
  """Emit a C boolean expression for a comparison."""
  field_name = cmp.field.name
  if field_name == ast.FIELD_PROTO:
    return _emit_proto_compare(cmp)
  if field_name in ast.IP_FIELDS:
    return _emit_ip_compare(cmp)
  if field_name in ast.PORT_FIELDS:
    return _emit_port_compare(cmp)
  raise NotImplementedError(
    f"emitter: comparison on {field_name} not supported"
  )


def _emit_proto_compare(cmp: ast.Comparison) -> str:
  """proto == tcp / proto != udp / etc."""
  ipproto = _PROTO_TO_IPPROTO[cmp.operand.proto]  # type: ignore[union-attr]
  return f"(proto {cmp.op} {ipproto})"


def _emit_ip_compare(cmp: ast.Comparison) -> str:
  """src_ip/dst_ip comparisons (== / != / in)."""
  c_field = _FIELD_TO_C[cmp.field.name]
  if cmp.op in ("==", "!="):
    val = cmp.operand.value  # type: ignore[union-attr]
    return f"({c_field} {cmp.op} 0x{val:08X}u)"
  if cmp.op == "in":
    return _emit_ip_in(c_field, cmp.operand)
  raise NotImplementedError(
    f"emitter: ip op {cmp.op} not supported"
  )


def _emit_ip_in(c_field: str, operand: ast.Operand) -> str:
  """Emit a C expression for `<ip_field> in <operand>`."""
  if isinstance(operand, ast.CidrLiteral):
    return _emit_cidr_match(c_field, operand)
  if isinstance(operand, ast.CidrListLiteral):
    parts = [_emit_cidr_match(c_field, c) for c in operand.items]
    return "(" + " || ".join(parts) + ")"
  if isinstance(operand, ast.ListLiteral):
    parts = [
      f"({c_field} == 0x{item.value:08X}u)"
      for item in operand.items
      if isinstance(item, ast.IPv4Literal)
    ]
    return "(" + " || ".join(parts) + ")"
  raise NotImplementedError(
    f"emitter: ip 'in' operand {type(operand).__name__} not supported"
  )


def _emit_cidr_match(c_field: str, cidr: ast.CidrLiteral) -> str:
  """Emit a C expression for a CIDR membership test."""
  if cidr.bits == 0:
    return "1"
  mask = ((1 << cidr.bits) - 1) << (32 - cidr.bits)
  return (
    f"(({c_field} & 0x{mask:08X}u) == 0x{cidr.prefix:08X}u)"
  )


def _emit_port_compare(cmp: ast.Comparison) -> str:
  """Port comparisons (== / != / < / > / <= / >= / in)."""
  c_field = _FIELD_TO_C[cmp.field.name]
  if cmp.op in ("==", "!=", "<", ">", "<=", ">="):
    val = cmp.operand.value  # type: ignore[union-attr]
    return f"({c_field} {cmp.op} {val})"
  if cmp.op == "in":
    return _emit_port_in(c_field, cmp.operand)
  raise NotImplementedError(
    f"emitter: port op {cmp.op} not supported"
  )


def _emit_port_in(c_field: str, operand: ast.Operand) -> str:
  """Emit a C expression for `<port_field> in <operand>`."""
  if isinstance(operand, ast.RangeLiteral):
    return f"({c_field} >= {operand.lo} && {c_field} <= {operand.hi})"
  if isinstance(operand, ast.ListLiteral):
    parts = [
      f"({c_field} == {item.value})"
      for item in operand.items
      if isinstance(item, ast.IntLiteral)
    ]
    return "(" + " || ".join(parts) + ")"
  raise NotImplementedError(
    f"emitter: port 'in' operand {type(operand).__name__} not supported"
  )


def _emit_rule(
  rule: ast.Rule, idx: int, counter_slots: dict[str, int]
) -> str:
  """Emit C statements for one rule.

  Terminal actions return; non-terminal actions execute their side
  effect and fall through to the next rule. A rate_limit modifier
  gates the entire rule body — when blocked, neither the action's
  side effect nor return fires.
  """
  if rule.action in _TERMINAL_ACTION_TO_RETURN:
    ret = _TERMINAL_ACTION_TO_RETURN[rule.action]
    if rule.modifier is not None:
      fire_block = _emit_rate_limit_gate(rule.modifier, idx, ret)
    else:
      fire_block = f"return {ret};"
  else:
    # Non-terminal: emit the side effect, no return.
    if rule.action == ast.Action.LOG:
      side_effect = _emit_log(idx)
    elif rule.action == ast.Action.COUNT:
      slot = counter_slots[rule.counter_name]  # type: ignore[index]
      side_effect = _emit_count(slot)
    else:
      raise NotImplementedError(
        f"emitter: unsupported action {rule.action}"
      )
    if rule.modifier is not None:
      fire_block = _emit_rate_limit_side_effect(
        rule.modifier, idx, side_effect
      )
    else:
      fire_block = side_effect

  if rule.condition is None:
    return f"  {{\n    {fire_block}\n  }}\n"
  expr = _emit_condition(rule.condition)
  return f"  if ({expr}) {{\n    {fire_block}\n  }}\n"


def _emit_log(rule_idx: int) -> str:
  """Emit code that submits a log_event for rule `rule_idx`."""
  return f"""struct fwl_log_event *ev =
      bpf_ringbuf_reserve(&fwl_log_events, sizeof(*ev), 0);
    if (ev) {{
      ev->timestamp_ns = bpf_ktime_get_ns();
      ev->src_ip = src_ip;
      ev->dst_ip = dst_ip;
      ev->src_port = src_port;
      ev->dst_port = dst_port;
      ev->proto = proto;
      ev->flags = (tcp_syn ? 0x01 : 0) | (tcp_ack ? 0x02 : 0);
      ev->rule_index = {rule_idx};
      bpf_ringbuf_submit(ev, 0);
    }}"""


def _emit_count(slot: int) -> str:
  """Emit code that bumps the counter at `slot`."""
  return f"""__u32 ck = {slot};
    __u64 *cnt = bpf_map_lookup_elem(&fwl_counters, &ck);
    if (cnt) {{
      __sync_fetch_and_add(cnt, 1);
    }}"""


def _emit_rate_limit_side_effect(
  mod: ast.RateLimit, idx: int, side_effect: str
) -> str:
  """Wrap a non-terminal side effect with rate_limit gating."""
  c_field = _RL_FIELD_TO_C[mod.per_field]
  return f"""__u32 rl_key = (__u32){c_field};
    __u64 now = bpf_ktime_get_ns();
    struct fwl_rl_state *st =
      bpf_map_lookup_elem(&fwl_rl_map_{idx}, &rl_key);
    __u32 cur = 0;
    __u64 cur_ts = now;
    if (st && now - st->ts < 1000000000ULL) {{
      cur = st->count;
      cur_ts = st->ts;
    }}
    if (cur < {mod.threshold}) {{
      struct fwl_rl_state new_st = {{ .ts = cur_ts, .count = cur + 1 }};
      bpf_map_update_elem(&fwl_rl_map_{idx}, &rl_key, &new_st, BPF_ANY);
      {side_effect}
    }}"""


def _emit_rate_limit_gate(mod: ast.RateLimit, idx: int, ret: str) -> str:
  """Emit a rate-limit gate that returns `ret` only if under threshold.

  Reads the bucket counter from the per-CPU map; if (now - ts) >= 1s
  the counter resets. The rule fires when the post-window count is
  strictly less than the threshold and the count is then incremented.
  """
  c_field = _RL_FIELD_TO_C[mod.per_field]
  return f"""__u32 rl_key = (__u32){c_field};
    __u64 now = bpf_ktime_get_ns();
    struct fwl_rl_state *st =
      bpf_map_lookup_elem(&fwl_rl_map_{idx}, &rl_key);
    __u32 cur = 0;
    __u64 cur_ts = now;
    if (st && now - st->ts < 1000000000ULL) {{
      cur = st->count;
      cur_ts = st->ts;
    }}
    if (cur < {mod.threshold}) {{
      struct fwl_rl_state new_st = {{ .ts = cur_ts, .count = cur + 1 }};
      bpf_map_update_elem(&fwl_rl_map_{idx}, &rl_key, &new_st, BPF_ANY);
      return {ret};
    }}"""


def _emit_rl_maps(program: ast.Program) -> str:
  """Emit per-CPU hash map declarations for each rate_limit modifier."""
  blocks: list[str] = []
  for idx, rule in enumerate(program.rules):
    if rule.modifier is None:
      continue
    blocks.append(f"""\
struct {{
  __uint(type, BPF_MAP_TYPE_PERCPU_HASH);
  __type(key, __u32);
  __type(value, struct fwl_rl_state);
  __uint(max_entries, 4096);
}} fwl_rl_map_{idx} SEC(".maps");
""")
  return "\n".join(blocks)


def emit(program: ast.Program) -> str:
  """Emit BPF C source for `program`."""
  prelude = _emit_parse_prelude(program)
  rl_maps = _emit_rl_maps(program)

  counter_slots = _allocate_counter_slots(program)
  has_log = any(r.action == ast.Action.LOG for r in program.rules)

  log_decl = _LOG_EVENT_DECL if has_log else ""
  if counter_slots:
    counter_decl = _COUNTER_MAP_DECL_TEMPLATE.format(
      n_slots=max(len(counter_slots), 1)
    )
    counter_table = _emit_counter_table(counter_slots)
  else:
    counter_decl = ""
    counter_table = ""

  body = "".join(
    _emit_rule(r, i, counter_slots) for i, r in enumerate(program.rules)
  )

  if program.default is not None:
    final_return = _TERMINAL_ACTION_TO_RETURN[program.default.action]
  else:
    final_return = "XDP_PASS"

  return f"""{_HEADER}
{log_decl}{counter_decl}{rl_maps}
SEC("xdp")
int fwl_prog(struct xdp_md *ctx) {{
{prelude}{body}  return {final_return};
}}

char _license[] SEC("license") = "GPL";
{counter_table}"""


def _allocate_counter_slots(program: ast.Program) -> dict[str, int]:
  """Assign a stable per-CPU array slot to each named counter.

  Slots are allocated in order of first appearance in the program;
  userspace tools read the name->slot mapping from the emitted
  fwl_counter_table comment block.
  """
  slots: dict[str, int] = {}
  for rule in program.rules:
    if rule.action != ast.Action.COUNT:
      continue
    name = rule.counter_name
    if name is None:
      continue
    if name not in slots:
      slots[name] = len(slots)
  return slots


def _emit_counter_table(slots: dict[str, int]) -> str:
  """Emit a comment block mapping counter names to their slot indices.

  Userspace tools parse this to look up counters by their declared
  identifier without needing the .fw source.
  """
  lines = ["// fwl_counter_table:"]
  for name, slot in slots.items():
    lines.append(f"//   {slot}\t{name}")
  return "\n".join(lines) + "\n"
