"""`.pkt` test format loader and packet builder mini-language.

A `.pkt` file is a YAML document. The `test_packet.builder` field is a
small expression language — NOT eval'd Python — describing how to
build the test packet. Builder syntax:

    tcp(src_ip="1.2.3.4", dst_port=22, syn=true, ack=false)
    udp(dst_ip="8.8.8.8", dst_port=53)
    icmp(src_ip="1.1.1.1")

The builder produces raw Ethernet+IPv4+L4 bytes for BPF_PROG_RUN
together with a decoded-fields dict the AST interpreter consumes.

Why a parsed mini-language and not eval'd Python: corpus content is
generated by AI agents and reviewed by humans. eval()ing
agent-generated code would be a security and correctness footgun for
zero gain — the mini-language is ~80 lines of straightforward parsing.
"""
from __future__ import annotations
import re
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True)
class Packet:
  """A test packet: raw Ethernet frame + decoded fields.

  `raw` is what BPF_PROG_RUN sees. `fields` is what the AST
  interpreter consumes. Both are derived from the same builder call
  so the two oracles see consistent inputs.
  """
  raw: bytes
  fields: dict[str, Any]


@dataclass(frozen=True)
class PktCase:
  """A loaded `.pkt` test case.

  `state` carries pre-existing rate-limit bucket counts keyed by
  rule index. Format in the .pkt file:

    state:
      rate_limit:
        0: { "1.2.3.4": 5 }    # rule index 0, bucket "1.2.3.4" = 5

  Empty dict when the file omits a `state:` block.
  """
  name: str
  source_fw: str
  packet: Packet
  expected: dict[str, Any]
  state: dict[int, dict[Any, int]]
  path: Path


_BUILDER_RE = re.compile(
  r"""
  ^\s*
  (?P<proto>tcp|udp|icmp)
  \s*\(\s*
  (?P<args>.*?)
  \s*\)\s*$
  """,
  re.VERBOSE,
)


def _parse_value(text: str) -> Any:
  """Parse one builder argument value: int, bool, or quoted string."""
  text = text.strip()
  if text == "true":
    return True
  if text == "false":
    return False
  if text.startswith('"') and text.endswith('"'):
    return text[1:-1]
  if re.fullmatch(r"-?\d+", text):
    return int(text)
  if re.fullmatch(r"0x[0-9a-fA-F]+", text):
    return int(text, 16)
  raise ValueError(f"unrecognized builder value: {text!r}")


def _split_args(args_text: str) -> list[tuple[str, str]]:
  """Split `a=1, b="x", c=true` honoring quoted strings.

  v0.1 builder values don't include commas inside strings or nested
  parens, so a small state-machine split is enough.
  """
  if not args_text.strip():
    return []
  parts: list[str] = []
  current: list[str] = []
  in_string = False
  for ch in args_text:
    if ch == '"':
      in_string = not in_string
      current.append(ch)
    elif ch == "," and not in_string:
      parts.append("".join(current))
      current = []
    else:
      current.append(ch)
  parts.append("".join(current))

  result: list[tuple[str, str]] = []
  for part in parts:
    if "=" not in part:
      raise ValueError(
        f"builder argument missing '=': {part!r}"
      )
    name, _, value = part.partition("=")
    result.append((name.strip(), value.strip()))
  return result


def parse_builder(text: str) -> dict[str, Any]:
  """Parse a builder expression into a dict of decoded fields.

  Returns a dict containing at least `proto`. Other keys depend on
  the builder used.
  """
  match = _BUILDER_RE.match(text)
  if not match:
    raise ValueError(f"unrecognized builder expression: {text!r}")
  fields: dict[str, Any] = {"proto": match.group("proto")}
  for name, raw_value in _split_args(match.group("args")):
    fields[name] = _parse_value(raw_value)
  return fields


_DEFAULT_SRC_MAC = b"\x02\x00\x00\x00\x00\x01"
_DEFAULT_DST_MAC = b"\x02\x00\x00\x00\x00\x02"
_ETH_P_IP = 0x0800
_IPPROTO_TCP = 6
_IPPROTO_UDP = 17
_IPPROTO_ICMP = 1


def _ipv4_to_bytes(addr: str) -> bytes:
  """Pack a dotted-quad IPv4 string as 4 big-endian bytes."""
  parts = addr.split(".")
  if len(parts) != 4:
    raise ValueError(f"not an IPv4 dotted quad: {addr!r}")
  return bytes(int(p) for p in parts)


def _ipv4_checksum(header: bytes) -> int:
  """One's-complement sum over the IPv4 header words."""
  total = 0
  for i in range(0, len(header), 2):
    total += (header[i] << 8) | header[i + 1]
  while total >> 16:
    total = (total & 0xFFFF) + (total >> 16)
  return (~total) & 0xFFFF


def build_packet(fields: dict[str, Any]) -> Packet:
  """Build a Packet from a decoded-fields dict.

  Sensible defaults are filled in for missing fields so corpus
  authors only specify what matters for their test:

    src_ip = "1.1.1.1", dst_ip = "2.2.2.2"
    src_port = 12345, dst_port = 80   (TCP/UDP only)
    syn = false, ack = false          (TCP only)
  """
  proto = fields["proto"]
  src_ip = fields.get("src_ip", "1.1.1.1")
  dst_ip = fields.get("dst_ip", "2.2.2.2")

  if proto == "tcp":
    proto_num = _IPPROTO_TCP
    src_port = fields.get("src_port", 12345)
    dst_port = fields.get("dst_port", 80)
    syn = fields.get("syn", False)
    ack = fields.get("ack", False)
    flags = (0x02 if syn else 0) | (0x10 if ack else 0)
    # data offset = 5 (no options), reserved = 0
    data_offset_reserved = 0x50
    l4 = struct.pack(
      ">HHIIBBHHH",
      src_port, dst_port,
      0,                         # seq
      0,                         # ack_seq
      data_offset_reserved,
      flags,
      8192,                      # window
      0,                         # checksum (left zero for tests)
      0,                         # urgent
    )
    decoded = dict(fields)
    decoded.setdefault("src_ip", src_ip)
    decoded.setdefault("dst_ip", dst_ip)
    decoded.setdefault("src_port", src_port)
    decoded.setdefault("dst_port", dst_port)
    decoded.setdefault("syn", syn)
    decoded.setdefault("ack", ack)
  elif proto == "udp":
    proto_num = _IPPROTO_UDP
    src_port = fields.get("src_port", 12345)
    dst_port = fields.get("dst_port", 53)
    udp_len = 8
    l4 = struct.pack(
      ">HHHH", src_port, dst_port, udp_len, 0
    )
    decoded = dict(fields)
    decoded.setdefault("src_ip", src_ip)
    decoded.setdefault("dst_ip", dst_ip)
    decoded.setdefault("src_port", src_port)
    decoded.setdefault("dst_port", dst_port)
  elif proto == "icmp":
    proto_num = _IPPROTO_ICMP
    # type=8 (echo request), code=0, checksum=0, id=0, seq=0
    l4 = struct.pack(">BBHHH", 8, 0, 0, 0, 0)
    decoded = dict(fields)
    decoded.setdefault("src_ip", src_ip)
    decoded.setdefault("dst_ip", dst_ip)
  else:
    raise ValueError(f"unknown proto: {proto!r}")

  total_len = 20 + len(l4)
  ip_header = struct.pack(
    ">BBHHHBBH4s4s",
    0x45,                         # version=4, IHL=5
    0,                            # DSCP/ECN
    total_len,
    0,                            # id
    0,                            # flags + frag offset
    64,                           # TTL
    proto_num,
    0,                            # checksum placeholder
    _ipv4_to_bytes(src_ip),
    _ipv4_to_bytes(dst_ip),
  )
  checksum = _ipv4_checksum(ip_header)
  ip_header = ip_header[:10] + struct.pack(">H", checksum) + ip_header[12:]

  eth = _DEFAULT_DST_MAC + _DEFAULT_SRC_MAC + struct.pack(">H", _ETH_P_IP)
  raw = eth + ip_header + l4
  return Packet(raw=raw, fields=decoded)


def load(path: Path) -> PktCase:
  """Load a `.pkt` YAML file from disk."""
  text = path.read_text(encoding="utf-8")
  doc = yaml.safe_load(text)

  builder_text = doc["test_packet"]["builder"]
  fields = parse_builder(builder_text)
  packet = build_packet(fields)

  raw_state = (doc.get("state") or {}).get("rate_limit", {})
  state: dict[int, dict[Any, int]] = {}
  for rule_idx, buckets in raw_state.items():
    state[int(rule_idx)] = dict(buckets)

  return PktCase(
    name=doc["name"],
    source_fw=doc["source_fw"],
    packet=packet,
    expected=doc["expected"],
    state=state,
    path=path,
  )
