"""`.pkt` test format loader and packet builder mini-language.

A `.pkt` file is a YAML document. The `test_packet.builder` field is a
small expression language — NOT eval'd Python — describing how to
build the test packet. Builder syntax:

    tcp(src_ip="1.2.3.4", dst_port=22, syn=true, ack=false)
    udp(dst_ip="8.8.8.8", dst_port=53)
    icmp(src_ip="1.1.1.1")

The builder produces raw Ethernet+IPv4+L4 bytes for BPF_PROG_RUN
together with a decoded-fields dict the AST interpreter consumes.

Why a parsed mini-language and not eval'd Python: corpus content is
generated by AI agents and reviewed by humans. eval()ing
agent-generated code would be a security and correctness footgun for
zero gain — the mini-language is ~80 lines of straightforward parsing.
"""
from __future__ import annotations
import re
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


@dataclass(frozen=True)
class Packet:
  """A test packet: raw Ethernet frame + decoded fields.

  `raw` is what BPF_PROG_RUN sees. `fields` is what the AST
  interpreter consumes. Both are derived from the same builder call
  so the two oracles see consistent inputs.
  """
  raw: bytes
  fields: dict[str, Any]


@dataclass(frozen=True)
class PktCase:
  """A loaded `.pkt` test case.

  `state` carries pre-existing rate-limit bucket counts keyed by
  rule index. Format in the .pkt file:

    state:
      rate_limit:
        0: { "1.2.3.4": 5 }    # rule index 0, bucket "1.2.3.4" = 5

  Empty dict when the file omits a `state:` block.

  `geoip_data` carries a country-code → CIDR-list mapping (v0.2)
  used by geoip(...) lookups. Mirrors the bundle's `geoip.json`.
  Format in the .pkt file:

    geoip_data:
      RU: ["5.8.0.0/16", "2a00:1370::/32"]
      CN: ["1.0.1.0/24"]

  Empty dict when the file omits a `geoip_data:` block — geoip
  lookups against an empty dict always miss.
  """
  name: str
  source_fw: str
  packet: Packet
  expected: dict[str, Any]
  state: dict[int, dict[Any, int]]
  path: Path
  geoip_data: dict[str, list[str]] = None  # type: ignore[assignment]
  # v0.4 conntrack. `conntrack_seed` holds pre-existing forward
  # 5-tuple keys (proto str, src u32, dst u32, sport, dport) from the
  # `state.conntrack` block — both oracles start with these entries
  # present. `sequence`, when set, makes this a multi-packet case: an
  # ordered list of PktStep run against one carried-over conntrack
  # table (interpreter) / one loaded BPF object (bpf).
  conntrack_seed: tuple = ()
  sequence: tuple = None  # type: ignore[assignment]
  # v0.4 § 6: the zone the packet arrives on, naming which @xdp block
  # evaluates it in a multi-zone unit. None selects the first/only
  # block (the degenerate single-zone case).
  ingress_zone: str = None  # type: ignore[assignment]
  # Phase 5 NAT. `nat_masq_ip` is the masquerade source (the WAN IP the
  # `state.nat.masq_ip` block supplies, a 32-bit int) and `nat_mappings`
  # the pre-seeded reply mappings for return-traffic de-NAT: each a tuple
  # `(proto_str, src_u32, dst_u32, src_port, dst_port, new_u32,
  # new_port, kind)` where kind is 'snat' or 'dnat'.
  nat_masq_ip: int = None  # type: ignore[assignment]
  nat_mappings: tuple = ()


@dataclass(frozen=True)
class PktStep:
  """One ordered packet in a multi-packet `sequence:` case (v0.4)."""
  name: str
  packet: Packet
  expected: dict[str, Any]


_BUILDER_RE = re.compile(
  r"""
  ^\s*
  (?P<proto>tcp6|udp6|icmp6|tcp|udp|icmp|eth)
  \s*\(\s*
  (?P<args>.*?)
  \s*\)\s*$
  """,
  re.VERBOSE,
)


def _parse_value(text: str) -> Any:
  """Parse one builder argument value: int, bool, or quoted string."""
  text = text.strip()
  if text == "true":
    return True
  if text == "false":
    return False
  if text.startswith('"') and text.endswith('"'):
    return text[1:-1]
  if re.fullmatch(r"-?\d+", text):
    return int(text)
  if re.fullmatch(r"0x[0-9a-fA-F]+", text):
    return int(text, 16)
  raise ValueError(f"unrecognized builder value: {text!r}")


def _split_args(args_text: str) -> list[tuple[str, str]]:
  """Split `a=1, b="x", c=true` honoring quoted strings.

  v0.1 builder values don't include commas inside strings or nested
  parens, so a small state-machine split is enough.
  """
  if not args_text.strip():
    return []
  parts: list[str] = []
  current: list[str] = []
  in_string = False
  for ch in args_text:
    if ch == '"':
      in_string = not in_string
      current.append(ch)
    elif ch == "," and not in_string:
      parts.append("".join(current))
      current = []
    else:
      current.append(ch)
  parts.append("".join(current))

  result: list[tuple[str, str]] = []
  for part in parts:
    if "=" not in part:
      raise ValueError(
        f"builder argument missing '=': {part!r}"
      )
    name, _, value = part.partition("=")
    result.append((name.strip(), value.strip()))
  return result


# v0.4 adds the six remaining TCP flags to the tcp/tcp6 builders and
# type/code to the icmp/icmp6 builders (f-04a), plus the VLAN tag
# fields to every builder (f-04b).
_TCP_BUILDER_FIELDS = frozenset({
  "src_ip", "dst_ip", "src_port", "dst_port",
  "syn", "ack", "fin", "rst", "psh", "urg", "ece", "cwr",
})
# Shared VLAN builder fields: the outer tag (vlan_id/vlan_priority)
# plus the optional inner tag (inner_vlan_id/inner_vlan_priority) that
# produces a double-tagged QinQ frame for the outer-only-parse tests.
# Every builder accepts these and inserts a 4-byte 802.1Q tag after
# the source MAC (FWL_V04_SPEC.md "Builder additions").
_VLAN_BUILDER_FIELDS = frozenset({
  "vlan_id", "vlan_priority", "inner_vlan_id", "inner_vlan_priority",
})
# Malformed/edge IPv4 header knobs, accepted by the v4 builders only.
# `ihl` writes the IHL nibble (and inserts (ihl-5)*4 bytes of NOP
# options when > 5) so a case can reach the emitter's header-length
# guard and the NAT helper's `ip->ihl != 5` bail-out; `udp_csum_zero`
# emits the RFC 768 "no checksum" datagram the NAT rewrite must leave
# alone. Both are branch-coverage instruments: nothing else in the
# builder language can produce those frames.
_IPV4_EDGE_FIELDS = frozenset({"ihl"})
# The raw L2 builder. Every other builder in this file produces an IPv4
# or IPv6 frame, so the EtherType is always 0x0800 or 0x86DD and the
# emitted program's non-IP arm — `fwl_l3p != ETH_P_IP && fwl_l3p !=
# ETH_P_IPV6` — has never been taken by any corpus case, in any of the
# 90 programs that contain it.
#
# That arm is not an academic gap. The box this compiler targets goes
# into a single flat L2 office network, where ARP, LLDP, STP BPDUs and
# misdelivered junk are the NORMAL traffic. The emitter has a
# deliberate gate for it (emitter.py `_emit_parse_prelude`, the
# no-referenced-fields branch): FWL has no L2 fields, so no construct
# can meaningfully act on an L2 control frame, and a program built from
# unconditional actions otherwise WOULD — an unconditional `redirect`
# re-emits the switch's own BPDUs out another port and real switch
# fabric answers by blocking it. Found on an EX2300 by the storm_shield
# hardware test; veth-based tests cannot see it.
#
# So the builder needs a way to make a frame that is not IP. Fields:
#   ethertype    required, 0..0xFFFF. A value <= 1500 is an IEEE 802.3
#                LENGTH field rather than an EtherType — which is
#                exactly how an STP BPDU is framed, and it must reach
#                the same arm.
#   payload_len  bytes after the EtherType; default 46, the Ethernet
#                minimum, giving a 60-byte frame.
#   payload_hex  a real protocol body instead of filler, so a case can
#                document what an actual ARP request or LLDP TLV chain
#                looks like on this wire.
_ETH_BUILDER_FIELDS = frozenset({
  "ethertype", "payload_len", "payload_hex",
})
_BUILDER_FIELD_TABLE: dict[str, frozenset[str]] = {
  "eth": _ETH_BUILDER_FIELDS | _VLAN_BUILDER_FIELDS,
  "tcp": (_TCP_BUILDER_FIELDS | _VLAN_BUILDER_FIELDS
          | _IPV4_EDGE_FIELDS),
  "udp": (frozenset({"src_ip", "dst_ip", "src_port", "dst_port",
                     "udp_csum_zero"})
          | _VLAN_BUILDER_FIELDS | _IPV4_EDGE_FIELDS),
  "icmp": (frozenset({"src_ip", "dst_ip", "type", "code"})
           | _VLAN_BUILDER_FIELDS | _IPV4_EDGE_FIELDS),
  # v0.2 IPv6 builders. Per PKT_V02_SPEC.md, the field names src_ip
  # and dst_ip are reused for symmetry with the v4 builders; the
  # values are RFC 4291 IPv6 strings, so the type is unambiguous to
  # the loader. src_ip6 and dst_ip6 are NOT separate fields on the v6
  # builders.
  "tcp6": _TCP_BUILDER_FIELDS | _VLAN_BUILDER_FIELDS,
  "udp6": frozenset({"src_ip", "dst_ip", "src_port",
                     "dst_port"}) | _VLAN_BUILDER_FIELDS,
  "icmp6": frozenset({"src_ip", "dst_ip", "type",
                      "code"}) | _VLAN_BUILDER_FIELDS,
}

# TCP flag bit positions in the flags byte (TCP header offset 13).
_TCP_FLAG_BITS = (
  ("fin", 0x01),
  ("syn", 0x02),
  ("rst", 0x04),
  ("psh", 0x08),
  ("ack", 0x10),
  ("urg", 0x20),
  ("ece", 0x40),
  ("cwr", 0x80),
)


def _tcp_flags_byte(fields: dict[str, Any]) -> int:
  """Assemble the TCP flags byte from the builder's bool fields."""
  flags = 0
  for name, bit in _TCP_FLAG_BITS:
    if fields.get(name, False):
      flags |= bit
  return flags


def _set_tcp_flag_decoded(decoded: dict[str, Any], fields: dict[str, Any]):
  """Default every TCP flag to False on the decoded-fields dict."""
  for name, _bit in _TCP_FLAG_BITS:
    decoded.setdefault(name, bool(fields.get(name, False)))


def parse_builder(text: str) -> dict[str, Any]:
  """Parse a builder expression into a dict of decoded fields.

  Returns a dict containing at least `proto`. Other keys depend on
  the builder used; per PKT_V01_SPEC.md:253, names not in the
  proto's field table are rejected at load time.
  """
  match = _BUILDER_RE.match(text)
  if not match:
    raise ValueError(f"unrecognized builder expression: {text!r}")
  proto = match.group("proto")
  allowed = _BUILDER_FIELD_TABLE[proto]
  fields: dict[str, Any] = {"proto": proto}
  for name, raw_value in _split_args(match.group("args")):
    if name not in allowed:
      raise ValueError(f"unknown {proto} field {name!r}")
    fields[name] = _parse_value(raw_value)
  return fields


# Decoded-field groups the emitted parser gates behind `l4_ok` and
# `icmp_ok` / `icmp6_ok`. Shared by the truncation mirror and the IHL
# mirror so the two cannot drift apart.
_L4_GATED_KEYS = (
  "src_port", "dst_port",
  "syn", "ack", "fin", "rst", "psh", "urg", "ece", "cwr",
)
_ICMP_GATED_KEYS = ("icmp_type", "icmp_code", "icmp6_type", "icmp6_code")

_DEFAULT_SRC_MAC = b"\x02\x00\x00\x00\x00\x01"
_DEFAULT_DST_MAC = b"\x02\x00\x00\x00\x00\x02"
_ETH_P_IP = 0x0800
_ETH_P_IPV6 = 0x86DD
_ETH_P_8021Q = 0x8100
_IPPROTO_TCP = 6
_IPPROTO_UDP = 17
_IPPROTO_ICMP = 1
_IPPROTO_ICMPV6 = 58
_DEFAULT_V6_SRC = "2001:db8::1"
_DEFAULT_V6_DST = "2001:db8::2"


def _vlan_tci(vlan_id: int, vlan_priority: int) -> int:
  """Pack a 16-bit 802.1Q TCI: PCP(3) | DEI(1)=0 | VID(12)."""
  return ((vlan_priority & 0x7) << 13) | (vlan_id & 0x0FFF)


def _validated_vlan(vlan_id: Any, vlan_priority: Any) -> tuple[int, int]:
  """Resolve + range-check a (vid, pcp) pair, defaulting absent to 0."""
  vid = 0 if vlan_id is None else int(vlan_id)
  pcp = 0 if vlan_priority is None else int(vlan_priority)
  if not (0 <= vid <= 4095):
    raise ValueError(f"vlan_id out of range 0..4095: {vid}")
  if not (0 <= pcp <= 7):
    raise ValueError(f"vlan_priority out of range 0..7: {pcp}")
  return vid, pcp


def _eth_header(
  ether_type: int,
  vlan_id: Any,
  vlan_priority: Any,
  inner_vlan_id: Any = None,
  inner_vlan_priority: Any = None,
) -> tuple[bytes, dict[str, int], bool]:
  """Build the Ethernet header, inserting 802.1Q tag(s) if requested.

  Returns (header_bytes, vlan_decoded, is_qinq). When either vlan_id
  or vlan_priority is supplied, a 4-byte tag (TPID 0x8100 + TCI) is
  inserted after the source MAC and `vlan_decoded` carries the
  outer vlan_id/vlan_priority keys; otherwise the tag is absent and
  `vlan_decoded` is empty (an untagged frame, unchanged from
  pre-v0.4). When an inner tag is also supplied (QinQ), a second
  0x8100 tag follows the outer one and `is_qinq` is True — v0.4
  parses the outer tag only, so the caller drops the (now
  unreachable) L3/L4 decoded fields. `ether_type` is always the real
  L3 type (0x0800/0x86DD) and follows the tag stack.
  """
  has_outer = vlan_id is not None or vlan_priority is not None
  has_inner = inner_vlan_id is not None or inner_vlan_priority is not None
  header = _DEFAULT_DST_MAC + _DEFAULT_SRC_MAC
  vlan_decoded: dict[str, int] = {}
  if has_outer or has_inner:
    vid, pcp = _validated_vlan(vlan_id, vlan_priority)
    header += struct.pack(">HH", _ETH_P_8021Q, _vlan_tci(vid, pcp))
    vlan_decoded = {"vlan_id": vid, "vlan_priority": pcp}
    if has_inner:
      ivid, ipcp = _validated_vlan(inner_vlan_id, inner_vlan_priority)
      header += struct.pack(">HH", _ETH_P_8021Q, _vlan_tci(ivid, ipcp))
  header += struct.pack(">H", ether_type)
  return header, vlan_decoded, has_inner


def _ipv4_to_bytes(addr: Any, field: str = "ip") -> bytes:
  """Pack a dotted-quad IPv4 string as 4 big-endian bytes.

  Raises ValueError with the offending field name when `addr` isn't
  a dotted-quad string. Without this, an int passed for `src_ip`
  (e.g. `tcp(src_ip=16909060)`) crashes with an opaque AttributeError
  deep in the builder — surfaced by the explore-mode bug hunter.
  """
  if not isinstance(addr, str):
    raise ValueError(
      f"{field}: expected dotted-quad string, got "
      f"{type(addr).__name__} ({addr!r})"
    )
  parts = addr.split(".")
  if len(parts) != 4:
    raise ValueError(f"{field}: not an IPv4 dotted quad: {addr!r}")
  try:
    octets = [int(p) for p in parts]
  except ValueError:
    raise ValueError(f"{field}: not an IPv4 dotted quad: {addr!r}")
  for octet in octets:
    if not (0 <= octet <= 255):
      raise ValueError(f"{field}: IPv4 octet out of range 0..255: {octet}")
  return bytes(octets)


def _ipv4_checksum(header: bytes) -> int:
  """One's-complement sum over the IPv4 header words."""
  total = 0
  for i in range(0, len(header), 2):
    total += (header[i] << 8) | header[i + 1]
  while total >> 16:
    total = (total & 0xFFFF) + (total >> 16)
  return (~total) & 0xFFFF


def _l4_checksum(src4: bytes, dst4: bytes, proto_num: int,
                 l4: bytes) -> int:
  """TCP/UDP checksum over the IPv4 pseudo-header + L4 segment.

  Built frames carry a *valid* L4 checksum so a NAT rewrite (which
  updates it incrementally) can be checked on the wire — the BPF
  oracle recomputes it after every translation."""
  data = (src4 + dst4 + bytes([0, proto_num])
          + len(l4).to_bytes(2, "big") + l4)
  if len(data) % 2:
    data += b"\x00"
  total = 0
  for i in range(0, len(data), 2):
    total += (data[i] << 8) | data[i + 1]
  while total >> 16:
    total = (total & 0xFFFF) + (total >> 16)
  return (~total) & 0xFFFF


def _ipv6_to_bytes(addr: Any, field: str = "ip") -> bytes:
  """Pack an RFC 5952 canonical IPv6 string as 16 big-endian bytes (v0.2).

  Per PKT_V02_SPEC.md, builder field values must be RFC 5952
  canonical — the same discipline parser._parse_ipv6 enforces on
  .fw source literals. Without this gate, corpus authors can write
  tests whose source strings the .fw program can't contain.
  """
  import ipaddress as _ipaddress
  if not isinstance(addr, str):
    raise ValueError(
      f"{field}: expected IPv6 string, got "
      f"{type(addr).__name__} ({addr!r})"
    )
  try:
    parsed = _ipaddress.IPv6Address(addr)
  except _ipaddress.AddressValueError as e:
    raise ValueError(
      f"{field}: not a valid IPv6 address: {addr!r}"
    ) from e
  expected = _canonical_ipv6_for_builder(addr, parsed)
  if addr != expected:
    raise ValueError(
      f"builder {field}: {addr!r} must be RFC 5952 canonical IPv6 "
      f"(expected {expected!r})"
    )
  return parsed.packed


_IPV4_MAPPED_BLOCK_BUILDER = None


def _canonical_ipv6_for_builder(text, addr) -> str:
  """RFC 5952 canonical form for a builder field — mirrors parser.

  Rules 1-3 via IPv6Address.compressed; rule 4 (RFC 5952 §5)
  applies dotted-quad to the ::ffff:0:0/96 IPv4-mapped block. The
  parser holds an identical helper; lifting them into a shared
  module is a follow-up.
  """
  import ipaddress as _ipaddress
  global _IPV4_MAPPED_BLOCK_BUILDER
  if _IPV4_MAPPED_BLOCK_BUILDER is None:
    _IPV4_MAPPED_BLOCK_BUILDER = _ipaddress.IPv6Network("::ffff:0:0/96")
  if addr in _IPV4_MAPPED_BLOCK_BUILDER:
    v4 = _ipaddress.IPv4Address(int(addr) & 0xFFFFFFFF)
    return f"::ffff:{v4}"
  return addr.compressed


def _build_v6_packet(fields: dict[str, Any]) -> Packet:
  """Build a Packet for an IPv6 builder (tcp6/udp6/icmp6) — v0.2.

  Produces an Ethernet frame with EtherType 0x86DD, an IPv6 fixed
  header (40 bytes: version=6, traffic class=0, flow label=0,
  payload length, next header, hop limit=64, src/dst addresses), and
  the L4 header. No extension headers; ICMPv6 is type 128 (Echo
  Request). The decoded-fields dict carries `src_ip6`/`dst_ip6` keys
  (not `src_ip`/`dst_ip`) so a v0.1-shaped rule reading `pkt.src_ip`
  finds the field absent and falls through, matching FWL_V02_SPEC.md's
  cross-family rule.

  Per PKT_V02_SPEC.md, the `proto` key in the decoded dict is the
  wire-level next_header value translated to a v0.1-style keyword
  string (`tcp` for next_header=6, `udp` for 17, `icmp6` for 58).
  Whether a v0.1-shaped program SEES this proto value is governed by
  the v6-surface-activation rule the interpreter applies separately.
  """
  proto = fields["proto"]
  src = fields.get("src_ip", _DEFAULT_V6_SRC)
  dst = fields.get("dst_ip", _DEFAULT_V6_DST)

  if proto == "tcp6":
    next_header = _IPPROTO_TCP
    proto_str = "tcp"
    src_port = fields.get("src_port", 12345)
    dst_port = fields.get("dst_port", 80)
    flags = _tcp_flags_byte(fields)
    data_offset_reserved = 0x50
    l4 = struct.pack(
      ">HHIIBBHHH",
      src_port, dst_port,
      0, 0,
      data_offset_reserved, flags,
      8192, 0, 0,
    )
    decoded = {
      "ether_type": _ETH_P_IPV6,
      "proto": proto_str,
      "src_ip6": src,
      "dst_ip6": dst,
      "src_port": src_port,
      "dst_port": dst_port,
    }
    _set_tcp_flag_decoded(decoded, fields)
  elif proto == "udp6":
    next_header = _IPPROTO_UDP
    proto_str = "udp"
    src_port = fields.get("src_port", 12345)
    dst_port = fields.get("dst_port", 53)
    udp_len = 8
    l4 = struct.pack(">HHHH", src_port, dst_port, udp_len, 0)
    decoded = {
      "ether_type": _ETH_P_IPV6,
      "proto": proto_str,
      "src_ip6": src,
      "dst_ip6": dst,
      "src_port": src_port,
      "dst_port": dst_port,
    }
  else:
    # icmp6
    next_header = _IPPROTO_ICMPV6
    proto_str = "icmp6"
    # type defaults to 128 (Echo Request); code defaults to 0.
    # checksum, id, seq are left zero for tests.
    icmp6_type = fields.get("type", 128)
    icmp6_code = fields.get("code", 0)
    l4 = struct.pack(">BBHHH", icmp6_type, icmp6_code, 0, 0, 0)
    decoded = {
      "ether_type": _ETH_P_IPV6,
      "proto": proto_str,
      "src_ip6": src,
      "dst_ip6": dst,
      "icmp6_type": icmp6_type,
      "icmp6_code": icmp6_code,
    }

  payload_len = len(l4)
  # IPv6 fixed header: 4 bytes version+TC+flow, 2 bytes payload length,
  # 1 byte next header, 1 byte hop limit, 16 bytes src, 16 bytes dst.
  ipv6_header = (
    struct.pack(">IHBB", 0x60000000, payload_len, next_header, 64)
    + _ipv6_to_bytes(src, "src_ip")
    + _ipv6_to_bytes(dst, "dst_ip")
  )
  eth, vlan_decoded, is_qinq = _eth_header(
    _ETH_P_IPV6, fields.get("vlan_id"), fields.get("vlan_priority"),
    fields.get("inner_vlan_id"), fields.get("inner_vlan_priority"),
  )
  decoded = vlan_decoded if is_qinq else {**decoded, **vlan_decoded}
  raw = eth + ipv6_header + l4
  return Packet(raw=raw, fields=decoded)


# Ethernet's minimum payload. 46 + 14 = the 60-byte frame a real NIC
# emits; anything shorter is padded on the wire, so a case that wants
# a short frame should say so with `truncate_to` rather than by
# building an impossible one.
_ETH_MIN_PAYLOAD = 46
_ETH_MAX_PAYLOAD = 1500


def _validated_ethertype(raw: Any) -> int:
  """Range-check the eth builder's `ethertype`."""
  if raw is None:
    raise ValueError("eth() requires an ethertype")
  if isinstance(raw, bool) or not isinstance(raw, int):
    raise ValueError(
      f"eth ethertype must be an integer 0..65535: {raw!r}"
    )
  if not (0 <= raw <= 0xFFFF):
    raise ValueError(f"eth ethertype out of range 0..65535: {raw}")
  return raw


def _eth_payload(fields: dict[str, Any]) -> bytes:
  """The bytes after the EtherType, from `payload_hex` or a length."""
  raw_hex = fields.get("payload_hex")
  length = fields.get("payload_len")
  if raw_hex is not None and length is not None:
    raise ValueError(
      "eth() takes payload_hex OR payload_len, not both — padding one "
      "to the other would silently change the frame a case documents"
    )
  if raw_hex is not None:
    if not isinstance(raw_hex, str):
      raise ValueError(f"eth payload_hex must be a string: {raw_hex!r}")
    text = raw_hex.replace(" ", "").replace(":", "")
    try:
      body = bytes.fromhex(text)
    except ValueError:
      raise ValueError(f"eth payload_hex is not hex: {raw_hex!r}")
    if len(body) > _ETH_MAX_PAYLOAD:
      raise ValueError(
        f"eth payload_hex is {len(body)} bytes, over the "
        f"{_ETH_MAX_PAYLOAD}-byte Ethernet MTU"
      )
    return body
  if length is None:
    return b"\x00" * _ETH_MIN_PAYLOAD
  if isinstance(length, bool) or not isinstance(length, int):
    raise ValueError(f"eth payload_len must be an integer: {length!r}")
  if not (0 <= length <= _ETH_MAX_PAYLOAD):
    raise ValueError(
      f"eth payload_len out of range 0..{_ETH_MAX_PAYLOAD}: {length}"
    )
  return b"\x00" * length


def _build_eth_frame(fields: dict[str, Any]) -> Packet:
  """Build a non-IP Ethernet frame: ARP, LLDP, an STP BPDU, junk.

  The decoded dict deliberately carries NO L3 or L4 field — not even
  `proto`. That is the whole contract with the interpreter: its
  `_non_ip_early_out` mirror keys on the presence of the L3 group
  (`proto`/`src_ip`/`dst_ip`/`src_ip6`/`dst_ip6`), and a frame that
  never parsed at L3 must leave that group empty or the two oracles
  disagree about which arm the compiled program took.

  `ether_type` IS carried, because two other mirrors read it: the NAT
  helper's `h_proto != bpf_htons(ETH_P_IP)` bail (interpreter.py) and
  the truncation mirror's v4/v6 offset choice. It is not an FWL packet
  field and no rule can read it.
  """
  ether_type = _validated_ethertype(fields.get("ethertype"))
  payload = _eth_payload(fields)
  eth, vlan_decoded, is_qinq = _eth_header(
    ether_type, fields.get("vlan_id"), fields.get("vlan_priority"),
    fields.get("inner_vlan_id"), fields.get("inner_vlan_priority"),
  )
  # `ether_type` here means "what the emitted parser RESOLVES to",
  # not "what the frame ultimately carries". v0.4 parses the outer tag
  # only, so behind a second tag the value it lands on is the inner
  # TPID — 0x8100, which is neither ETH_P_IP nor ETH_P_IPV6. That is
  # not a technicality: double-tagged frames are one of the things a
  # badly-segmented corporate LAN actually emits, and 802.1Q stacking
  # is only expressible as a non-IP frame because of it.
  resolved = _ETH_P_8021Q if is_qinq else ether_type
  decoded: dict[str, Any] = {"ether_type": resolved}
  decoded.update(vlan_decoded)
  return Packet(raw=eth + payload, fields=decoded)


def build_packet(fields: dict[str, Any]) -> Packet:
  """Build a Packet from a decoded-fields dict.

  Sensible defaults are filled in for missing fields so corpus
  authors only specify what matters for their test:

    src_ip = "1.1.1.1", dst_ip = "2.2.2.2"     (v4 builders)
    src_ip = "2001:db8::1", dst_ip = "::2"     (v6 builders)
    src_port = 12345, dst_port = 80            (TCP/UDP only)
    syn = false, ack = false                   (TCP only)

  v0.2 v6 builders (tcp6/udp6/icmp6) are dispatched to a separate
  helper because the IPv6 frame layout (40-byte fixed header,
  EtherType 0x86DD, 16-byte addresses, no checksum) differs from v4.
  """
  proto = fields["proto"]
  if proto == "eth":
    return _build_eth_frame(fields)
  if proto in ("tcp6", "udp6", "icmp6"):
    return _build_v6_packet(fields)
  src_ip = fields.get("src_ip", "1.1.1.1")
  dst_ip = fields.get("dst_ip", "2.2.2.2")

  if proto == "tcp":
    proto_num = _IPPROTO_TCP
    src_port = fields.get("src_port", 12345)
    dst_port = fields.get("dst_port", 80)
    flags = _tcp_flags_byte(fields)
    # data offset = 5 (no options), reserved = 0
    data_offset_reserved = 0x50
    l4 = struct.pack(
      ">HHIIBBHHH",
      src_port, dst_port,
      0,                         # seq
      0,                         # ack_seq
      data_offset_reserved,
      flags,
      8192,                      # window
      0,                         # checksum (left zero for tests)
      0,                         # urgent
    )
    decoded = dict(fields)
    decoded.setdefault("src_ip", src_ip)
    decoded.setdefault("dst_ip", dst_ip)
    decoded.setdefault("src_port", src_port)
    decoded.setdefault("dst_port", dst_port)
    _set_tcp_flag_decoded(decoded, fields)
  elif proto == "udp":
    proto_num = _IPPROTO_UDP
    src_port = fields.get("src_port", 12345)
    dst_port = fields.get("dst_port", 53)
    udp_len = 8
    l4 = struct.pack(
      ">HHHH", src_port, dst_port, udp_len, 0
    )
    decoded = dict(fields)
    decoded.setdefault("src_ip", src_ip)
    decoded.setdefault("dst_ip", dst_ip)
    decoded.setdefault("src_port", src_port)
    decoded.setdefault("dst_port", dst_port)
  elif proto == "icmp":
    proto_num = _IPPROTO_ICMP
    # type defaults to 8 (echo request); code defaults to 0. checksum,
    # id, seq are left zero for tests.
    icmp_type = fields.get("type", 8)
    icmp_code = fields.get("code", 0)
    l4 = struct.pack(">BBHHH", icmp_type, icmp_code, 0, 0, 0)
    decoded = dict(fields)
    decoded.pop("type", None)
    decoded.pop("code", None)
    decoded.setdefault("src_ip", src_ip)
    decoded.setdefault("dst_ip", dst_ip)
    decoded["icmp_type"] = icmp_type
    decoded["icmp_code"] = icmp_code
  else:
    raise ValueError(f"unknown proto: {proto!r}")

  ihl = _validated_ihl(fields.get("ihl"))
  # ihl > 5 means IP options: (ihl-5)*4 bytes between the fixed header
  # and L4. NOP (0x01) padding keeps the option area well-formed. ihl
  # < 5 is deliberately malformed — the nibble lies about a header that
  # is still 20 bytes, which is what the emitter's `ip_hlen >=
  # sizeof(struct iphdr)` guard exists to reject.
  opt_len = max(0, (ihl - 5) * 4)
  options = b"\x01" * opt_len
  total_len = 20 + opt_len + len(l4)
  ip_header = struct.pack(
    ">BBHHHBBH4s4s",
    0x40 | (ihl & 0x0F),          # version=4, IHL as requested
    0,                            # DSCP/ECN
    total_len,
    0,                            # id
    0,                            # flags + frag offset
    64,                           # TTL
    proto_num,
    0,                            # checksum placeholder
    _ipv4_to_bytes(src_ip, "src_ip"),
    _ipv4_to_bytes(dst_ip, "dst_ip"),
  )
  # The header checksum covers the options too (RFC 791), and the
  # runner's post-rewrite checksum diagnostic reads exactly ihl*4
  # bytes — computing it over the fixed header alone would report every
  # options frame as corrupt.
  checksum = _ipv4_checksum(ip_header + options)
  ip_header = ip_header[:10] + struct.pack(">H", checksum) + ip_header[12:]

  # Fill a valid TCP/UDP checksum (ICMP keeps its zero placeholder —
  # v0.4 NAT never rewrites ICMP, so no oracle checks it). The L4
  # checksum field sits at offset 16 (TCP) / 6 (UDP).
  src4 = _ipv4_to_bytes(src_ip, "src_ip")
  dst4 = _ipv4_to_bytes(dst_ip, "dst_ip")
  if proto == "tcp":
    c = _l4_checksum(src4, dst4, proto_num, l4)
    l4 = l4[:16] + struct.pack(">H", c) + l4[18:]
  elif proto == "udp":
    # RFC 768 lets a UDP sender skip the checksum by transmitting zero.
    # The emitter's NAT rewrite is required to leave such a datagram's
    # checksum at zero rather than "fixing" it, so the builder has to
    # be able to produce one.
    if fields.get("udp_csum_zero"):
      c = 0
    else:
      c = _l4_checksum(src4, dst4, proto_num, l4) or 0xFFFF
    l4 = l4[:6] + struct.pack(">H", c) + l4[8:]

  eth, vlan_decoded, is_qinq = _eth_header(
    _ETH_P_IP, fields.get("vlan_id"), fields.get("vlan_priority"),
    fields.get("inner_vlan_id"), fields.get("inner_vlan_priority"),
  )
  # v0.4 parses the outer tag only: behind a second tag the L3/L4
  # headers are unreachable, so the decoded dict exposes just the
  # outer VLAN fields (mirrors the emitter leaving v4_ok/l4_ok at 0).
  decoded = vlan_decoded if is_qinq else {**decoded, **vlan_decoded}
  decoded = _apply_ihl_to_decoded(decoded, ihl, is_qinq)
  raw = eth + ip_header + options + l4
  return Packet(raw=raw, fields=decoded)


# Builder-only keys: they shape the frame but are not FWL packet
# fields, so they must not survive into the decoded dict a rule reads.
_NON_FIELD_BUILDER_KEYS = ("ihl", "udp_csum_zero")


def _validated_ihl(raw: Any) -> int:
  """Resolve + range-check the builder's `ihl`, defaulting to 5."""
  if raw is None:
    return 5
  if isinstance(raw, bool) or not isinstance(raw, int):
    raise ValueError(f"builder ihl must be an integer 0..15: {raw!r}")
  if not (0 <= raw <= 15):
    raise ValueError(f"builder ihl out of range 0..15: {raw}")
  return raw


def _apply_ihl_to_decoded(
  decoded: dict[str, Any], ihl: int, is_qinq: bool
) -> dict[str, Any]:
  """Mirror the emitter's IHL guard on the decoded-fields dict.

  The emitted prelude parses L4 only inside
  `if (ip_hlen >= sizeof(struct iphdr) && (void *)ip + ip_hlen <=
  data_end)`, so an IHL below 5 leaves `l4_ok` / `icmp_ok` at zero and
  every port, TCP-flag and ICMP field unreadable. The interpreter
  consumes this dict, so it has to lose the same fields or the two
  oracles disagree on a frame neither of them is wrong about.

  `_ihl` is recorded (never stripped) because the NAT helpers bail on
  `ip->ihl != 5` — the interpreter's NAT model reads it to mirror that
  bail-out. The leading underscore keeps it out of the FWL field
  namespace.
  """
  out = dict(decoded)
  for key in _NON_FIELD_BUILDER_KEYS:
    out.pop(key, None)
  if is_qinq:
    # A double-tagged frame exposes no L3/L4 fields at all; the IHL of
    # an unreachable header is not a property anything can observe.
    return out
  out["_ihl"] = ihl
  if ihl >= 5:
    return out
  for key in _L4_GATED_KEYS + _ICMP_GATED_KEYS:
    out.pop(key, None)
  return out


_TOP_LEVEL_KEYS = frozenset({
  "name", "source_fw", "test_packet", "expected", "state", "geoip_data",
  # v0.4: a multi-packet conntrack test. Mutually exclusive with the
  # single test_packet/expected pair.
  "sequence",
  # v0.4 § 6: names the ingress zone (which @xdp block) for a multi-zone
  # unit. Omitted for single-zone files.
  "ingress_zone",
})
_TEST_PACKET_KEYS = frozenset({"builder", "truncate_to"})
_EXPECTED_KEYS = frozenset({
  "compiles", "bpf_action", "counter_changes", "log_events",
  "load_action", "load_error_pattern", "loads",
  # Hunt-emitted assertion text. The runner does not consume it
  # today — wiring it through the analyzer is a v0.3 backlog item.
  "compile_error_pattern",
  # v0.4 § 6.3: for a `redirect` bpf_action, the expected destination
  # zone (checked by the interpreter oracle).
  "redirect_zone",
  # Phase 5 NAT: the expected packet header fields after the program's
  # NAT rewrite. A mapping of {src_ip, dst_ip, src_port, dst_port} —
  # only the keys present are checked. Verified by both oracles.
  "output_packet",
})
# v0.4 adds `conntrack`; Phase 5 adds `nat` (masquerade IP + pre-seeded
# reply mappings) alongside the v0.1 `rate_limit` bucket state.
_STATE_KEYS = frozenset({"rate_limit", "conntrack", "nat"})
_OUTPUT_PACKET_KEYS = frozenset({
  "src_ip", "dst_ip", "src_port", "dst_port",
})
_NAT_STATE_KEYS = frozenset({"masq_ip", "mappings"})
_NAT_MAPPING_KEYS = frozenset({
  "proto", "src_ip", "dst_ip", "src_port", "dst_port",
  "new_ip", "new_port", "nat_type",
})
_SEQUENCE_STEP_KEYS = frozenset({"name", "builder", "truncate_to", "expected"})
_CONNTRACK_ENTRY_KEYS = frozenset({
  "src_ip", "dst_ip", "src_port", "dst_port", "proto",
})
# v0.4 conntrack tracks IPv4 only (the daemon's ConnKey is 32-bit), so
# the seed proto is one of these three.
_CONNTRACK_PROTO_NUM = {
  "tcp": _IPPROTO_TCP,
  "udp": _IPPROTO_UDP,
  "icmp": _IPPROTO_ICMP,
}


def _ipv4_str_to_int(addr: str, where: str) -> int:
  """Dotted-quad to host-order u32 (high octet first), with validation."""
  if not isinstance(addr, str):
    raise ValueError(f"{where}: expected dotted-quad string, got {addr!r}")
  parts = addr.split(".")
  if len(parts) != 4:
    raise ValueError(f"{where}: not an IPv4 dotted quad: {addr!r}")
  value = 0
  for part in parts:
    n = int(part)
    if not (0 <= n <= 255):
      raise ValueError(f"{where}: IPv4 octet out of range 0..255: {n}")
    value = (value << 8) | n
  return value


def _parse_nat_state(raw: Any) -> tuple:
  """Parse `state.nat` into `(masq_ip_int_or_None, mappings_tuple)`.

  `masq_ip` is the masquerade source IPv4. `mappings` is a list of
  reply-direction entries used to de-NAT return traffic; each carries
  the forward 5-tuple the return packet presents (proto/src_ip/dst_ip/
  src_port/dst_port), the address+port to restore (new_ip/new_port), and
  the direction `nat_type` ('snat' rewrites source, 'dnat' rewrites
  destination). Returned mappings are
  `(proto, src_u32, dst_u32, sport, dport, new_u32, new_port, kind)`.
  """
  if raw is None:
    return (None, ())
  if not isinstance(raw, dict):
    raise ValueError("state.nat must be a mapping")
  _reject_unknown_keys(raw, _NAT_STATE_KEYS, "state.nat")
  masq = raw.get("masq_ip")
  masq_ip = (_ipv4_str_to_int(masq, "state.nat.masq_ip")
             if masq is not None else None)
  out: list[tuple] = []
  for i, m in enumerate(raw.get("mappings") or []):
    if not isinstance(m, dict):
      raise ValueError(f"state.nat.mappings[{i}] must be a mapping")
    _reject_unknown_keys(m, _NAT_MAPPING_KEYS, f"state.nat.mappings[{i}]")
    proto = m.get("proto")
    if proto not in _CONNTRACK_PROTO_NUM:
      raise ValueError(
        f"state.nat.mappings[{i}].proto must be tcp/udp/icmp"
      )
    kind = m.get("nat_type")
    if kind not in ("snat", "dnat"):
      raise ValueError(
        f"state.nat.mappings[{i}].nat_type must be snat or dnat"
      )
    w = f"state.nat.mappings[{i}]"
    out.append((
      proto,
      _ipv4_str_to_int(m["src_ip"], f"{w}.src_ip"),
      _ipv4_str_to_int(m["dst_ip"], f"{w}.dst_ip"),
      int(m.get("src_port", 0)),
      int(m.get("dst_port", 0)),
      _ipv4_str_to_int(m["new_ip"], f"{w}.new_ip"),
      int(m.get("new_port", 0)),
      kind,
    ))
  return (masq_ip, tuple(out))


def _parse_conntrack_seed(raw: Any) -> tuple:
  """Parse `state.conntrack` into normalized forward 5-tuple keys.

  Each entry is a mapping with src_ip/dst_ip/proto (required) and
  optional src_port/dst_port (default 0, as for ICMP). v0.4 conntrack
  is IPv4-only, so v6 addresses are rejected. The returned keys match
  the interpreter's `ConntrackTable` format:
  `(proto_str, src_u32, dst_u32, src_port, dst_port)`.
  """
  if raw is None:
    return ()
  if not isinstance(raw, list):
    raise ValueError("state.conntrack must be a list of entries")
  out: list[tuple] = []
  for i, entry in enumerate(raw):
    if not isinstance(entry, dict):
      raise ValueError(f"state.conntrack[{i}] must be a mapping")
    _reject_unknown_keys(
      entry, _CONNTRACK_ENTRY_KEYS, f"state.conntrack[{i}]"
    )
    proto = entry.get("proto")
    if proto not in _CONNTRACK_PROTO_NUM:
      raise ValueError(
        f"state.conntrack[{i}].proto must be one of "
        f"tcp/udp/icmp (v0.4 conntrack is IPv4-only); got {proto!r}"
      )
    if "src_ip" not in entry or "dst_ip" not in entry:
      raise ValueError(
        f"state.conntrack[{i}] requires src_ip and dst_ip"
      )
    src = _ipv4_str_to_int(entry["src_ip"], f"state.conntrack[{i}].src_ip")
    dst = _ipv4_str_to_int(entry["dst_ip"], f"state.conntrack[{i}].dst_ip")
    sport = int(entry.get("src_port", 0))
    dport = int(entry.get("dst_port", 0))
    out.append((proto, src, dst, sport, dport))
  return tuple(out)


def _reject_unknown_keys(
  block: dict, allowed: frozenset[str], where: str,
) -> None:
  """Per PKT_V01_SPEC.md:39, unknown keys at any documented level
  are validation errors — silently discarding typos breaks tests."""
  for key in block:
    if key not in allowed:
      raise ValueError(f"unknown field {key!r} at {where}")


def _build_from_spec(builder_text: str, truncate_to: Any) -> Packet:
  """Build a Packet from a builder string + optional truncate_to.

  truncate_to (optional) truncates the built packet to N bytes and
  strips the decoded fields that would land past it, mirroring the
  BPF parser's bounds checks so the two oracles agree on partial
  frames (PKT_V01_SPEC.md "test_packet").
  """
  fields = parse_builder(builder_text)
  packet = build_packet(fields)
  if truncate_to is not None:
    if not isinstance(truncate_to, int) or truncate_to < 0:
      raise ValueError("truncate_to must be ≥ 0")
    if truncate_to < len(packet.raw):
      packet = Packet(
        raw=packet.raw[:truncate_to],
        fields=_strip_truncated_fields(packet.fields, truncate_to),
      )
  return packet


def _parse_rate_limit_state(doc: dict) -> dict[int, dict[Any, int]]:
  """Parse + validate the `state.rate_limit` block.

  Per PKT_V01_SPEC.md:256, every key must reference a rule index that
  exists AND carries a rate_limit modifier; bucket counts must be
  non-negative integers.
  """
  raw_state = (doc.get("state") or {}).get("rate_limit", {})
  state: dict[int, dict[Any, int]] = {}
  if not raw_state:
    return state
  valid = _rate_limit_rule_indices(doc["source_fw"])
  for rule_idx, buckets in raw_state.items():
    idx = int(rule_idx)
    if idx not in valid:
      raise ValueError(
        f"state.rate_limit references rule index {idx} without a "
        f"rate_limit modifier"
      )
    for bucket_key, count in buckets.items():
      if not isinstance(count, int) or isinstance(count, bool):
        raise ValueError(
          f"state.rate_limit[{idx}][{bucket_key!r}] must be a "
          f"non-negative integer; got {count!r}"
        )
      if count < 0:
        raise ValueError(
          f"state.rate_limit[{idx}][{bucket_key!r}] must be a "
          f"non-negative integer; got {count}"
        )
    state[idx] = dict(buckets)
  return state


def _parse_geoip_data(doc: dict) -> dict[str, list[str]]:
  """Parse + validate the `geoip_data` block (v0.2)."""
  raw_geoip = doc.get("geoip_data") or {}
  geoip_data: dict[str, list[str]] = {}
  for code, prefixes in raw_geoip.items():
    if not isinstance(code, str) or len(code) != 2 or not code.isupper():
      raise ValueError(
        f"geoip_data key {code!r} must be an uppercase 2-letter "
        f"ISO 3166-1 alpha-2 country code"
      )
    if not isinstance(prefixes, list):
      raise ValueError(
        f"geoip_data[{code}] must be a list of CIDR strings"
      )
    geoip_data[code] = [str(p) for p in prefixes]
  return geoip_data


def _check_counter_changes_declared(doc: dict, expected: dict) -> None:
  """Reject counter_changes naming a counter the source doesn't declare."""
  counter_changes = expected.get("counter_changes", {})
  if counter_changes:
    declared = _declared_counter_names(doc["source_fw"])
    for name in counter_changes:
      if name not in declared:
        raise ValueError(f"counter '{name}' not declared in source_fw")


# The emitter appends this reserved slot to any program that uses a
# rate_limit primitive (emitter.RATE_LIMIT_OVERFLOW_COUNTER). It is not
# spelled by a `count` rule, so `_declared_counter_names` cannot see it,
# but it is the ONLY observable of a rate-limit map whose key space is
# exhausted — without it that path is unassertable from a .pkt.
RATE_LIMIT_OVERFLOW_COUNTER = "__rate_limit_overflow"


def _load_sequence(doc: dict, path: Path) -> PktCase:
  """Load a multi-packet `sequence:` case (v0.4 conntrack)."""
  raw_steps = doc["sequence"]
  if not isinstance(raw_steps, list) or not raw_steps:
    raise ValueError("sequence must be a non-empty list of steps")
  steps: list[PktStep] = []
  for i, raw in enumerate(raw_steps):
    _reject_unknown_keys(raw, _SEQUENCE_STEP_KEYS, f"sequence[{i}]")
    if "builder" not in raw or "expected" not in raw:
      raise ValueError(f"sequence[{i}] requires builder and expected")
    _reject_unknown_keys(
      raw["expected"], _EXPECTED_KEYS, f"sequence[{i}].expected"
    )
    _check_counter_changes_declared(doc, raw["expected"])
    packet = _build_from_spec(raw["builder"], raw.get("truncate_to"))
    steps.append(PktStep(
      name=raw.get("name", f"step {i}"),
      packet=packet,
      expected=raw["expected"],
    ))
  _seq_nat = _parse_nat_state((doc.get("state") or {}).get("nat"))
  return PktCase(
    name=doc["name"],
    source_fw=doc["source_fw"],
    # The first step doubles as the case's `packet`/`expected` so code
    # that peeks at those attributes stays valid; the runner drives the
    # full `sequence` list.
    packet=steps[0].packet,
    expected=steps[0].expected,
    state=_parse_rate_limit_state(doc),
    path=path,
    geoip_data=_parse_geoip_data(doc),
    conntrack_seed=_parse_conntrack_seed(
      (doc.get("state") or {}).get("conntrack")
    ),
    # `state.nat` was parsed for single-packet cases and silently
    # dropped for sequences, so a sequence could declare a masquerade
    # address or a reply mapping and have both oracles ignore it — the
    # assertion looked present and did nothing.
    nat_masq_ip=_seq_nat[0],
    nat_mappings=_seq_nat[1],
    sequence=tuple(steps),
    ingress_zone=doc.get("ingress_zone"),
  )


def load(path: Path) -> PktCase:
  """Load a `.pkt` YAML file from disk.

  Two shapes: a single `test_packet`/`expected` pair (v0.1+), or a
  v0.4 `sequence:` of ordered packets sharing one conntrack table.
  Both may carry a `state.conntrack` pre-seed block.
  """
  text = path.read_text(encoding="utf-8")
  doc = yaml.safe_load(text)
  _reject_unknown_keys(doc, _TOP_LEVEL_KEYS, "top level")
  if doc.get("state") is not None:
    _reject_unknown_keys(doc["state"], _STATE_KEYS, "state")

  if doc.get("sequence") is not None:
    if "test_packet" in doc or "expected" in doc:
      raise ValueError(
        "a sequence case must not also define test_packet/expected"
      )
    return _load_sequence(doc, path)

  _reject_unknown_keys(
    doc["test_packet"], _TEST_PACKET_KEYS, "test_packet"
  )
  _reject_unknown_keys(doc["expected"], _EXPECTED_KEYS, "expected")

  packet = _build_from_spec(
    doc["test_packet"]["builder"], doc["test_packet"].get("truncate_to")
  )
  state = _parse_rate_limit_state(doc)
  _check_counter_changes_declared(doc, doc["expected"])
  geoip_data = _parse_geoip_data(doc)
  conntrack_seed = _parse_conntrack_seed(
    (doc.get("state") or {}).get("conntrack")
  )
  nat_masq_ip, nat_mappings = _parse_nat_state(
    (doc.get("state") or {}).get("nat")
  )
  if "output_packet" in doc["expected"]:
    _reject_unknown_keys(
      doc["expected"]["output_packet"], _OUTPUT_PACKET_KEYS,
      "expected.output_packet",
    )

  return PktCase(
    name=doc["name"],
    source_fw=doc["source_fw"],
    packet=packet,
    expected=doc["expected"],
    state=state,
    path=path,
    geoip_data=geoip_data,
    conntrack_seed=conntrack_seed,
    ingress_zone=doc.get("ingress_zone"),
    nat_masq_ip=nat_masq_ip,
    nat_mappings=nat_mappings,
  )


def _strip_truncated_fields(
  fields: dict[str, Any], truncate_to: int
) -> dict[str, Any]:
  """Mirror the BPF parser's bounds-check on a truncated frame.

  Per the v0.2 emitter prelude: the parser bumps `v4_ok`/`v6_ok`
  only when the L3 header fits, and `l4_ok` only when the L4
  header fits. The decoded-field dict the interpreter consumes
  must reflect those gates by dropping fields the parser couldn't
  read on this truncated frame.

  Layout offsets (Ethernet II). A present 802.1Q tag shifts every
  L3/L4 offset by 4 (`l2_end` is 18 instead of 14):
    14 / 18       end of Ethernet header (untagged / tagged)
    +20           end of IPv4 fixed header (ihl=5)
    +40           end of IPv6 fixed header
    +20           full TCP header (ports + flag byte) readable

  VLAN-tag layout: TPID at 12, TCI at 14, inner EtherType at 16, so
  the vlan fields are readable once the 4-byte tag fits
  (truncate_to >= 16) and L3 begins at offset 18.

  Beyond v0.1's IHL≠5 case, the spec deferred extension headers,
  variable-IHL, and L4-after-IPv6-extensions, so this helper assumes
  the builder defaults (IHL=5, no v6 ext headers, single VLAN tag).
  """
  out = dict(fields)
  ether_type = out.get("ether_type")
  is_v6 = ether_type == 0x86DD
  # A present 802.1Q tag shifts every L3/L4 offset by 4 (l2_end is 18
  # instead of 14), so all boundaries below derive from l2_end.
  has_vlan = "vlan_id" in out or "vlan_priority" in out
  l2_end = 18 if has_vlan else 14
  l3_end = l2_end + (40 if is_v6 else 20)
  # L4 port/TCP-flag fields (gated by l4_ok) and ICMP type/code fields
  # (gated by icmp_ok/icmp6_ok) parse at different header sizes, so
  # they get separate truncation boundaries below.
  l4_keys = _L4_GATED_KEYS
  icmp_keys = _ICMP_GATED_KEYS
  # VLAN fields are readable only once the full 4-byte tag fits
  # (bytes 12..16). A frame truncated inside the tag leaves them
  # unreadable, mirroring the emitter's vlan_ok gate.
  if has_vlan and truncate_to < 16:
    out.pop("vlan_id", None)
    out.pop("vlan_priority", None)
  if truncate_to < l2_end:
    out.pop("ether_type", None)
  if truncate_to < l3_end:
    for key in (
      "proto", "src_ip", "dst_ip", "src_ip6", "dst_ip6",
    ):
      out.pop(key, None)
    for key in l4_keys + icmp_keys:
      out.pop(key, None)
    return out
  # The BPF emitter's L4 parse only sets `l4_ok` after a *full*
  # tcphdr/udphdr fits — not just the port pair. tcphdr is 20 B,
  # udphdr is 8 B. Use the conservative tcphdr-sized gate for both
  # so the interpreter mirrors BPF on every truncation boundary.
  if truncate_to < l3_end + 20:
    for key in l4_keys:
      out.pop(key, None)
  # The emitter reads ICMP/ICMPv6 type+code via a minimal 2-byte
  # struct fwl_icmphdr, setting icmp_ok/icmp6_ok only when those 2
  # bytes fit. Mirror that exact boundary.
  if truncate_to < l3_end + 2:
    for key in icmp_keys:
      out.pop(key, None)
  return out


def _rate_limit_rule_indices(source_fw: str) -> frozenset[int]:
  """Indices of rules in `source_fw` that carry a rate_limit modifier.

  Imported lazily to avoid an import cycle if the parser module ever
  grows a dependency on this one.
  """
  from . import analyzer, ast, parser
  program = analyzer.analyze(parser.parse(source_fw))
  return frozenset(
    idx for idx, rule in enumerate(program.rules)
    if isinstance(rule.modifier, ast.RateLimit)
  )


def _declared_counter_names(source_fw: str) -> frozenset[str]:
  """Counter names a .pkt may assert on for `source_fw`.

  `count <name>` rules, plus the reserved `__rate_limit_overflow` slot
  when the program carries any rate_limit modifier — the emitter
  allocates that slot itself, so a case can assert it without the
  policy naming it.
  """
  from . import analyzer, ast, parser
  program = analyzer.analyze(parser.parse(source_fw))
  reserved = (
    {RATE_LIMIT_OVERFLOW_COUNTER}
    if any(rule.modifier is not None for rule in program.rules)
    else set()
  )
  return frozenset(reserved) | frozenset(
    rule.counter_name
    for rule in program.rules
    if rule.action == ast.Action.COUNT and rule.counter_name
  )
